---
title: "scraper_v2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(stringr)
library(readr)
```



## Prepare links

Start: https://lopezobrador.org.mx/temas/version-estenografica/page/1/
Basis: https://lopezobrador.org.mx/temas/version-estenografica/page/X/

```{r }
# create sequence
seq <- seq(1,600,1) # here we can set the nr. of speeches
#seq


# create url
base_url <- "https://lopezobrador.org.mx/version-estenografica-de-la-conferencia-de-prensa-matutina-del-presidente-andres-manuel-lopez-obrador-"
url <- paste0(base_url,seq, "/")

#url
```



## Function to validate search URL
The validate returns true, when the requested website exists and has the title "Versión estenográfica" and "prensa matutina".
Otherwise it returns a false
```{r }
validate <- function(url) {
  
  page_title <- ""
  try({
    page_url <- read_html(url)
    node <- html_nodes(page_url, xpath = '/html/body/div[3]/div/div/div[1]/div/article/h1')
    page_title <- html_text(node)
    })
  
  return(page_title == "Versión estenográfica de la conferencia de prensa matutina del presidente Andrés Manuel López Obrador" )
  
  }

# test function

#validate("https://lopezobrador.org.mx/version-estenografica-de-la-conferencia-de-prensa-matutina-del-presidente-andres-manuel-lopez-obrador-629")

```


Function returns number of redirected URL
```{r }
speech_nr <- function(url) {
  redirected <- httr::GET(url)[["url"]]
  step1 <- sub(".*-", "", redirected)
  step2 <- sub("/$","", step1)
    return(step2)
}
```




## Code to scrape speeches and store them in .txt files

```{r }
folder <- "speeches/"
dir.create(folder)

for (i in 1:length(url)) {
  
  if(validate(url[i])){
    speech_url <- read_html(url[i])
    parsed_speech <- html_nodes(speech_url, xpath = '//p')
    parsed_date <- html_nodes(speech_url, xpath = '//*[contains(concat( " ", @class, " " ), concat( " ", "entry-date", " " ))]')
        
    speech <- html_text(parsed_speech)
    date <- html_text(parsed_date)%>%
      parse_date("%B %d, %Y", locale = locale("es"))
        
        if (speech_nr(url[i]) == seq[i] ){
          
          if (!file.exists(paste0(folder,date," no. ", seq[i]))) {
            
            write(speech, file = paste0(folder,date," no. ", seq[i]))
          }
        }
      }
  # timer (still needs to be set)  
      Sys.sleep(runif(1, 0, 1)) 
}
```



```{r }

```



```{r }

```



```{r }

```



```{r }

```



```{r }

```



```{r }

```



```{r }

```



```{r }

```
